name: Merge branch on push
on:
  push:
    branches:
      - 'testing'
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge testing -> main
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: testing
          target_branch: main
          github_token: ${{ github.token }}
